# Generated by Django 4.1.7 on 2023-03-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='alignment',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='monster',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='monster',
            name='size',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='monster',
            name='type',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
